# nonk8s
---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: "0.0.0.0"
  disableDefaultCNI: true
# featureGates:
#   EphemeralContainers: true
#   SeccompDefault: true
#   ServerSideApply: true
#   PodSecurity: true # migration from PodSecurityPolicy to PSS/PSA

# add to the apiServer certSANs the name of the docker (dind) service in order to be able to reach the cluster through it
#kubeadmConfigPatchesJSON6902:
#  - group: kubeadm.k8s.io
#    version: v1beta3
#    kind: ClusterConfiguration
#    patch: |
#      - op: add
#        path: /apiServer/certSANs/-
#        value: 172.17.0.1

nodes:
  - role: control-plane
    extraPortMappings:
      # default / Gateway controller / nginx-ingress-controller
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
      # cilium ingress-controller
      - containerPort: 32532
        hostPort: 32532
        protocol: TCP
      - containerPort: 32533
        hostPort: 32533
        protocol: TCP
#  - role: control-plane
#  - role: control-plane
#  - role: worker
