---
global:
  domain: argocd.127.0.0.1.nip.io
    # Default network policy rules used by all components
  networkPolicy:
    # -- Create NetworkPolicy objects for all components
    create: true
configs:
  # General Argo CD configuration. Any values you put under `.configs.cm` are passed to argocd-cm ConfigMap.
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  cm:
    # -- Create the argocd-cm configmap for [declarative setup]
    create: true

    # -- Enable logs RBAC enforcement
    ## Ref: https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/2.3-2.4/#enable-logs-rbac-enforcement
    server.rbac.log.enforce.enable: true

    # -- Enable exec feature in Argo UI
    ## Ref: https://argo-cd.readthedocs.io/en/latest/operator-manual/rbac/#exec-resource
    exec.enabled: true
  # Argo CD configuration parameters
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cmd-params-cm.yaml
  params:
    # -- Create the argocd-cmd-params-cm configmap
    # If false, it is expected the configmap will be created by something else.
    create: true

    # -- Annotations to be added to the argocd-cmd-params-cm ConfigMap
    annotations: {}

    ## Generic parameters
    # -- Open-Telemetry collector address: (e.g. "otel-collector:4317")
    otlp.address: ''

    ## Server properties
    # -- Run server without TLS
    ## NOTE: This value should be set when you generate params by other means as it changes ports used by ingress template.
    server.insecure: true
    # -- Value for base href in index.html. Used if Argo CD is running behind reverse proxy under subpath different from /
    # server.basehref: /
    # -- Used if Argo CD is running behind reverse proxy under subpath different from /
    # server.rootpath: ''
    # -- Disable Argo CD RBAC for user authentication
    server.disable.auth: true

    # -- Enables [Applications in any namespace]
    ## List of additional namespaces where applications may be created in and reconciled from.
    ## The namespace where Argo CD is installed to will always be allowed.
    ## Set comma-separated list. (e.g. app-team-one, app-team-two)
    application.namespaces: "monitoring"
    
dex:
  enabled: false
controller:
  metrics:
    enabled: true
repoServer:
  metrics:
    enabled: true
server:
  # config:
  #   url: http://argocd.127.0.0.1.nip.io
  metrics:
    enabled: true
  # extraArgs:
  #   - --insecure
  #   - --disable-auth
  ingress:
    enabled: true
    ingressClassName: cilium
    hosts:
      - argocd.127.0.0.1.nip.io
redis:
  metrics:
    enabled: true
applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

## Notifications controller
notifications:
  # -- Enable notifications controller
  enabled: true
  metrics:
    # -- Enables prometheus metrics server
    enabled: true

